# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polkitex.ui'
#
# Created: Tue Mar 26 14:37:05 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PolkitExplorer(object):
    def setupUi(self, PolkitExplorer):
        PolkitExplorer.setObjectName(_fromUtf8("PolkitExplorer"))
        PolkitExplorer.resize(910, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PolkitExplorer.sizePolicy().hasHeightForWidth())
        PolkitExplorer.setSizePolicy(sizePolicy)
        PolkitExplorer.setMinimumSize(QtCore.QSize(910, 530))
        PolkitExplorer.setMaximumSize(QtCore.QSize(910, 530))
        PolkitExplorer.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(PolkitExplorer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.polkitActionDescription = QtGui.QLabel(self.centralwidget)
        self.polkitActionDescription.setGeometry(QtCore.QRect(130, 290, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.polkitActionDescription.setFont(font)
        self.polkitActionDescription.setAutoFillBackground(True)
        self.polkitActionDescription.setFrameShape(QtGui.QFrame.Box)
        self.polkitActionDescription.setText(_fromUtf8(""))
        self.polkitActionDescription.setTextFormat(QtCore.Qt.PlainText)
        self.polkitActionDescription.setScaledContents(True)
        self.polkitActionDescription.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.polkitActionDescription.setObjectName(_fromUtf8("polkitActionDescription"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 350, 621, 101))
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.currentallowanylabel = QtGui.QLabel(self.frame)
        self.currentallowanylabel.setGeometry(QtCore.QRect(30, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentallowanylabel.setFont(font)
        self.currentallowanylabel.setFrameShape(QtGui.QFrame.WinPanel)
        self.currentallowanylabel.setFrameShadow(QtGui.QFrame.Raised)
        self.currentallowanylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentallowanylabel.setObjectName(_fromUtf8("currentallowanylabel"))
        self.currentallowanylabel_2 = QtGui.QLabel(self.frame)
        self.currentallowanylabel_2.setGeometry(QtCore.QRect(220, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentallowanylabel_2.setFont(font)
        self.currentallowanylabel_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.currentallowanylabel_2.setFrameShadow(QtGui.QFrame.Raised)
        self.currentallowanylabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.currentallowanylabel_2.setObjectName(_fromUtf8("currentallowanylabel_2"))
        self.currentallowanylabel_3 = QtGui.QLabel(self.frame)
        self.currentallowanylabel_3.setGeometry(QtCore.QRect(440, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentallowanylabel_3.setFont(font)
        self.currentallowanylabel_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.currentallowanylabel_3.setFrameShadow(QtGui.QFrame.Raised)
        self.currentallowanylabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.currentallowanylabel_3.setObjectName(_fromUtf8("currentallowanylabel_3"))
        self.currentAllowAnyLabel = QtGui.QLabel(self.frame)
        self.currentAllowAnyLabel.setGeometry(QtCore.QRect(20, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentAllowAnyLabel.setFont(font)
        self.currentAllowAnyLabel.setText(_fromUtf8(""))
        self.currentAllowAnyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentAllowAnyLabel.setObjectName(_fromUtf8("currentAllowAnyLabel"))
        self.currentAllowInactiveLabel = QtGui.QLabel(self.frame)
        self.currentAllowInactiveLabel.setGeometry(QtCore.QRect(210, 50, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentAllowInactiveLabel.setFont(font)
        self.currentAllowInactiveLabel.setText(_fromUtf8(""))
        self.currentAllowInactiveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentAllowInactiveLabel.setObjectName(_fromUtf8("currentAllowInactiveLabel"))
        self.currentAllowActiveLabel = QtGui.QLabel(self.frame)
        self.currentAllowActiveLabel.setGeometry(QtCore.QRect(420, 50, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentAllowActiveLabel.setFont(font)
        self.currentAllowActiveLabel.setText(_fromUtf8(""))
        self.currentAllowActiveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentAllowActiveLabel.setObjectName(_fromUtf8("currentAllowActiveLabel"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 891, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.WinPanel)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.policyKitFileName = QtGui.QLabel(self.centralwidget)
        self.policyKitFileName.setGeometry(QtCore.QRect(160, 20, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.policyKitFileName.setFont(font)
        self.policyKitFileName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.policyKitFileName.setFrameShadow(QtGui.QFrame.Sunken)
        self.policyKitFileName.setLineWidth(2)
        self.policyKitFileName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.policyKitFileName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.policyKitFileName.setObjectName(_fromUtf8("policyKitFileName"))
        self.polkitActionNameLabel = QtGui.QLabel(self.centralwidget)
        self.polkitActionNameLabel.setEnabled(True)
        self.polkitActionNameLabel.setGeometry(QtCore.QRect(10, 230, 891, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.polkitActionNameLabel.setFont(font)
        self.polkitActionNameLabel.setFrameShape(QtGui.QFrame.WinPanel)
        self.polkitActionNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polkitActionNameLabel.setObjectName(_fromUtf8("polkitActionNameLabel"))
        self.actionComboBox = QtGui.QComboBox(self.centralwidget)
        self.actionComboBox.setGeometry(QtCore.QRect(130, 240, 761, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.actionComboBox.setFont(font)
        self.actionComboBox.setObjectName(_fromUtf8("actionComboBox"))
        self.polkitActionNameLabel_2 = QtGui.QLabel(self.centralwidget)
        self.polkitActionNameLabel_2.setEnabled(True)
        self.polkitActionNameLabel_2.setGeometry(QtCore.QRect(10, 340, 891, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.polkitActionNameLabel_2.setFont(font)
        self.polkitActionNameLabel_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.polkitActionNameLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polkitActionNameLabel_2.setObjectName(_fromUtf8("polkitActionNameLabel_2"))
        self.polkitActionNameLabel_3 = QtGui.QLabel(self.centralwidget)
        self.polkitActionNameLabel_3.setEnabled(True)
        self.polkitActionNameLabel_3.setGeometry(QtCore.QRect(10, 80, 891, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.polkitActionNameLabel_3.setFont(font)
        self.polkitActionNameLabel_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.polkitActionNameLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.polkitActionNameLabel_3.setObjectName(_fromUtf8("polkitActionNameLabel_3"))
        self.actionsCounterDisplay = QtGui.QLCDNumber(self.centralwidget)
        self.actionsCounterDisplay.setGeometry(QtCore.QRect(20, 150, 131, 61))
        self.actionsCounterDisplay.setFrameShape(QtGui.QFrame.Panel)
        self.actionsCounterDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.actionsCounterDisplay.setObjectName(_fromUtf8("actionsCounterDisplay"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtGui.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        PolkitExplorer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PolkitExplorer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        PolkitExplorer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PolkitExplorer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PolkitExplorer.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(PolkitExplorer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAbout = QtGui.QAction(PolkitExplorer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(PolkitExplorer)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShow_Glossary = QtGui.QAction(PolkitExplorer)
        self.actionShow_Glossary.setObjectName(_fromUtf8("actionShow_Glossary"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionShow_Glossary)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PolkitExplorer)
        QtCore.QObject.connect(self.actionComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), PolkitExplorer.actionComboBoxChanged)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), PolkitExplorer.fileOpen)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), PolkitExplorer.fileQuit)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), PolkitExplorer.fileAbout)
        QtCore.QObject.connect(self.actionShow_Glossary, QtCore.SIGNAL(_fromUtf8("triggered()")), PolkitExplorer.helpGlossary)
        QtCore.QMetaObject.connectSlotsByName(PolkitExplorer)

    def retranslateUi(self, PolkitExplorer):
        PolkitExplorer.setWindowTitle(QtGui.QApplication.translate("PolkitExplorer", "Polkit Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.polkitActionDescription.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p>The Description of the Action as entered in the Policy file loaded. If no description is found this will tell you that fact.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.currentallowanylabel.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p>If set to &quot;yes&quot; will give any user permission to perform the action as described in the Description above. </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.currentallowanylabel.setText(QtGui.QApplication.translate("PolkitExplorer", "Allow Any", None, QtGui.QApplication.UnicodeUTF8))
        self.currentallowanylabel_2.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p>&quot;Inactive&quot; users are ones who are not directly logged into the system\'s console. This includes anyone who is logged in remotely, whether it be via ssh, telnet, or even RDP.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.currentallowanylabel_2.setText(QtGui.QApplication.translate("PolkitExplorer", "Allow Inactive", None, QtGui.QApplication.UnicodeUTF8))
        self.currentallowanylabel_3.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p>&quot;Active&quot; users are ones who are directly logged into a system\'s console, via a locally connected terminal. Users directly logged into a GUI at the system console, for example.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.currentallowanylabel_3.setText(QtGui.QApplication.translate("PolkitExplorer", "Allow Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PolkitExplorer", "Description :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PolkitExplorer", "Policy Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.policyKitFileName.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p>The full pathname of the currently opened Polkit policy file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.policyKitFileName.setText(QtGui.QApplication.translate("PolkitExplorer", "Please open a policy file...", None, QtGui.QApplication.UnicodeUTF8))
        self.polkitActionNameLabel.setText(QtGui.QApplication.translate("PolkitExplorer", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComboBox.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Drop-down list of all the actions within the policy file. Clicking on this will display the drop-down list, or you can use your scrollwheel to browse through them, too.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.polkitActionNameLabel_2.setText(QtGui.QApplication.translate("PolkitExplorer", "Policy", None, QtGui.QApplication.UnicodeUTF8))
        self.polkitActionNameLabel_3.setText(QtGui.QApplication.translate("PolkitExplorer", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionsCounterDisplay.setToolTip(QtGui.QApplication.translate("PolkitExplorer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Displays the number of Actions within a Polkit policy file.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PolkitExplorer", "# Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("PolkitExplorer", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("PolkitExplorer", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("PolkitExplorer", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("PolkitExplorer", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("PolkitExplorer", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Glossary.setText(QtGui.QApplication.translate("PolkitExplorer", "Show Glossary", None, QtGui.QApplication.UnicodeUTF8))

