# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'polkitex.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLCDNumber,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QTabWidget, QWidget)

class Ui_PolkitExplorer(object):
    def setupUi(self, PolkitExplorer):
        if not PolkitExplorer.objectName():
            PolkitExplorer.setObjectName(u"PolkitExplorer")
        PolkitExplorer.resize(910, 530)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PolkitExplorer.sizePolicy().hasHeightForWidth())
        PolkitExplorer.setSizePolicy(sizePolicy)
        PolkitExplorer.setMinimumSize(QSize(910, 530))
        PolkitExplorer.setMaximumSize(QSize(910, 530))
        PolkitExplorer.setTabShape(QTabWidget.TabShape.Rounded)
        self.action_open = QAction(PolkitExplorer)
        self.action_open.setObjectName(u"action_open")
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.action_open.setFont(font)
        self.action_about = QAction(PolkitExplorer)
        self.action_about.setObjectName(u"action_about")
        self.action_about.setFont(font)
        self.action_quit = QAction(PolkitExplorer)
        self.action_quit.setObjectName(u"action_quit")
        self.action_show_glossary = QAction(PolkitExplorer)
        self.action_show_glossary.setObjectName(u"action_show_glossary")
        self.centralwidget = QWidget(PolkitExplorer)
        self.centralwidget.setObjectName(u"centralwidget")
        self.polkitActionDescription = QLabel(self.centralwidget)
        self.polkitActionDescription.setObjectName(u"polkitActionDescription")
        self.polkitActionDescription.setGeometry(QRect(130, 290, 761, 31))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.polkitActionDescription.setFont(font1)
        self.polkitActionDescription.setAutoFillBackground(True)
        self.polkitActionDescription.setFrameShape(QFrame.Shape.StyledPanel)
        self.polkitActionDescription.setTextFormat(Qt.TextFormat.PlainText)
        self.polkitActionDescription.setScaledContents(True)
        self.polkitActionDescription.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(160, 350, 621, 101))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Sunken)
        self.currentallowanylabel = QLabel(self.frame)
        self.currentallowanylabel.setObjectName(u"currentallowanylabel")
        self.currentallowanylabel.setGeometry(QRect(30, 10, 131, 31))
        self.currentallowanylabel.setFont(font)
        self.currentallowanylabel.setFrameShape(QFrame.Shape.StyledPanel)
        self.currentallowanylabel.setFrameShadow(QFrame.Shadow.Raised)
        self.currentallowanylabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.currentallowanylabel_2 = QLabel(self.frame)
        self.currentallowanylabel_2.setObjectName(u"currentallowanylabel_2")
        self.currentallowanylabel_2.setGeometry(QRect(220, 10, 161, 31))
        self.currentallowanylabel_2.setFont(font)
        self.currentallowanylabel_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.currentallowanylabel_2.setFrameShadow(QFrame.Shadow.Raised)
        self.currentallowanylabel_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.currentallowanylabel_3 = QLabel(self.frame)
        self.currentallowanylabel_3.setObjectName(u"currentallowanylabel_3")
        self.currentallowanylabel_3.setGeometry(QRect(440, 10, 151, 31))
        self.currentallowanylabel_3.setFont(font)
        self.currentallowanylabel_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.currentallowanylabel_3.setFrameShadow(QFrame.Shadow.Raised)
        self.currentallowanylabel_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.currentAllowAnyLabel = QLabel(self.frame)
        self.currentAllowAnyLabel.setObjectName(u"currentAllowAnyLabel")
        self.currentAllowAnyLabel.setGeometry(QRect(20, 50, 151, 20))
        self.currentAllowAnyLabel.setFont(font)
        self.currentAllowAnyLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.currentAllowInactiveLabel = QLabel(self.frame)
        self.currentAllowInactiveLabel.setObjectName(u"currentAllowInactiveLabel")
        self.currentAllowInactiveLabel.setGeometry(QRect(210, 50, 181, 20))
        self.currentAllowInactiveLabel.setFont(font)
        self.currentAllowInactiveLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.currentAllowActiveLabel = QLabel(self.frame)
        self.currentAllowActiveLabel.setObjectName(u"currentAllowActiveLabel")
        self.currentAllowActiveLabel.setGeometry(QRect(420, 50, 191, 20))
        self.currentAllowActiveLabel.setFont(font)
        self.currentAllowActiveLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.currentAllowAnyLabel.raise_()
        self.currentAllowInactiveLabel.raise_()
        self.currentAllowActiveLabel.raise_()
        self.currentallowanylabel.raise_()
        self.currentallowanylabel_2.raise_()
        self.currentallowanylabel_3.raise_()
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 290, 101, 31))
        self.label_3.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 891, 61))
        font2 = QFont()
        font2.setFamilies([u"DejaVu Sans"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.label.setFont(font2)
        self.label.setFrameShape(QFrame.Shape.StyledPanel)
        self.label.setFrameShadow(QFrame.Shadow.Raised)
        self.label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.policyKitFileName = QLabel(self.centralwidget)
        self.policyKitFileName.setObjectName(u"policyKitFileName")
        self.policyKitFileName.setGeometry(QRect(160, 20, 721, 41))
        self.policyKitFileName.setFont(font)
        self.policyKitFileName.setFrameShape(QFrame.Shape.StyledPanel)
        self.policyKitFileName.setFrameShadow(QFrame.Shadow.Sunken)
        self.policyKitFileName.setLineWidth(2)
        self.policyKitFileName.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.policyKitFileName.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.polkitActionNameLabel = QLabel(self.centralwidget)
        self.polkitActionNameLabel.setObjectName(u"polkitActionNameLabel")
        self.polkitActionNameLabel.setEnabled(True)
        self.polkitActionNameLabel.setGeometry(QRect(10, 230, 891, 101))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(True)
        self.polkitActionNameLabel.setFont(font3)
        self.polkitActionNameLabel.setFrameShape(QFrame.Shape.StyledPanel)
        self.polkitActionNameLabel.setFrameShadow(QFrame.Shadow.Raised)
        self.polkitActionNameLabel.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.actionComboBox = QComboBox(self.centralwidget)
        self.actionComboBox.setObjectName(u"actionComboBox")
        self.actionComboBox.setGeometry(QRect(130, 240, 761, 29))
        self.actionComboBox.setFont(font)
        self.polkitActionNameLabel_2 = QLabel(self.centralwidget)
        self.polkitActionNameLabel_2.setObjectName(u"polkitActionNameLabel_2")
        self.polkitActionNameLabel_2.setEnabled(True)
        self.polkitActionNameLabel_2.setGeometry(QRect(10, 340, 891, 121))
        self.polkitActionNameLabel_2.setFont(font3)
        self.polkitActionNameLabel_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.polkitActionNameLabel_2.setFrameShadow(QFrame.Shadow.Raised)
        self.polkitActionNameLabel_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.polkitActionNameLabel_3 = QLabel(self.centralwidget)
        self.polkitActionNameLabel_3.setObjectName(u"polkitActionNameLabel_3")
        self.polkitActionNameLabel_3.setEnabled(True)
        self.polkitActionNameLabel_3.setGeometry(QRect(10, 80, 891, 141))
        self.polkitActionNameLabel_3.setFont(font3)
        self.polkitActionNameLabel_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.polkitActionNameLabel_3.setFrameShadow(QFrame.Shadow.Raised)
        self.polkitActionNameLabel_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.actionsCounterDisplay = QLCDNumber(self.centralwidget)
        self.actionsCounterDisplay.setObjectName(u"actionsCounterDisplay")
        self.actionsCounterDisplay.setGeometry(QRect(20, 150, 131, 61))
        self.actionsCounterDisplay.setFrameShape(QFrame.Shape.StyledPanel)
        self.actionsCounterDisplay.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 120, 131, 21))
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_2.setFrameShadow(QFrame.Shadow.Raised)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        PolkitExplorer.setCentralWidget(self.centralwidget)
        self.polkitActionNameLabel_2.raise_()
        self.polkitActionNameLabel.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.polkitActionNameLabel_3.raise_()
        self.label_2.raise_()
        self.policyKitFileName.raise_()
        self.actionsCounterDisplay.raise_()
        self.actionComboBox.raise_()
        self.polkitActionDescription.raise_()
        self.menubar = QMenuBar(PolkitExplorer)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 910, 27))
        self.menubar.setFont(font)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setFont(font)
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuHelp.setFont(font)
        PolkitExplorer.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(PolkitExplorer)
        self.statusbar.setObjectName(u"statusbar")
        PolkitExplorer.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.action_open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_about)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_show_glossary)

        self.retranslateUi(PolkitExplorer)
        self.actionComboBox.currentIndexChanged.connect(PolkitExplorer.actionComboBoxChanged)
        self.action_open.triggered.connect(PolkitExplorer.fileOpen)
        self.action_quit.triggered.connect(PolkitExplorer.fileQuit)
        self.action_about.triggered.connect(PolkitExplorer.fileAbout)
        self.action_show_glossary.triggered.connect(PolkitExplorer.helpGlossary)

        QMetaObject.connectSlotsByName(PolkitExplorer)
    # setupUi

    def retranslateUi(self, PolkitExplorer):
        PolkitExplorer.setWindowTitle(QCoreApplication.translate("PolkitExplorer", u"Polkit Explorer", None))
        self.action_open.setText(QCoreApplication.translate("PolkitExplorer", u"&Open", None))
        self.action_about.setText(QCoreApplication.translate("PolkitExplorer", u"&About", None))
        self.action_quit.setText(QCoreApplication.translate("PolkitExplorer", u"&Quit", None))
        self.action_show_glossary.setText(QCoreApplication.translate("PolkitExplorer", u"&Show Glossary", None))
#if QT_CONFIG(tooltip)
        self.polkitActionDescription.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p>The Description of the Action as entered in the Policy file loaded. If no description is found this will tell you that fact.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.polkitActionDescription.setText("")
#if QT_CONFIG(tooltip)
        self.currentallowanylabel.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p>If set to &quot;yes&quot; will give any user permission to perform the action as described in the Description above. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.currentallowanylabel.setText(QCoreApplication.translate("PolkitExplorer", u"Allow Any", None))
#if QT_CONFIG(tooltip)
        self.currentallowanylabel_2.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p>&quot;Inactive&quot; users are ones who are not directly logged into the system's console. This includes anyone who is logged in remotely, whether it be via ssh, telnet, or even RDP.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.currentallowanylabel_2.setText(QCoreApplication.translate("PolkitExplorer", u"Allow Inactive", None))
#if QT_CONFIG(tooltip)
        self.currentallowanylabel_3.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p>&quot;Active&quot; users are ones who are directly logged into a system's console, via a locally connected terminal. Users directly logged into a GUI at the system console, for example.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.currentallowanylabel_3.setText(QCoreApplication.translate("PolkitExplorer", u"Allow Active", None))
        self.currentAllowAnyLabel.setText("")
        self.currentAllowInactiveLabel.setText("")
        self.currentAllowActiveLabel.setText("")
        self.label_3.setText(QCoreApplication.translate("PolkitExplorer", u"Description :", None))
        self.label.setText(QCoreApplication.translate("PolkitExplorer", u"Policy Filename", None))
#if QT_CONFIG(tooltip)
        self.policyKitFileName.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p>The full pathname of the currently opened Polkit policy file.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.policyKitFileName.setText(QCoreApplication.translate("PolkitExplorer", u"Please open a policy file...", None))
        self.polkitActionNameLabel.setText(QCoreApplication.translate("PolkitExplorer", u"Action", None))
#if QT_CONFIG(tooltip)
        self.actionComboBox.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p><span style=\" font-weight:600;\">Drop-down list of all the actions within the policy file. Clicking on this will display the drop-down list, or you can use your scrollwheel to browse through them, too.</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.polkitActionNameLabel_2.setText(QCoreApplication.translate("PolkitExplorer", u"Policy", None))
        self.polkitActionNameLabel_3.setText(QCoreApplication.translate("PolkitExplorer", u"Info", None))
#if QT_CONFIG(tooltip)
        self.actionsCounterDisplay.setToolTip(QCoreApplication.translate("PolkitExplorer", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Displays the number of Actions within a Polkit policy file.</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("PolkitExplorer", u"# Actions", None))
        self.menuFile.setTitle(QCoreApplication.translate("PolkitExplorer", u"&File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("PolkitExplorer", u"&Help", None))
    # retranslateUi

